

export const cars = [
    {
        id: 0,
        make: 'Audi',
        price: 25,
        image:'../images/1200x900n.webp',
        model: 'A4',
        year: 2020,
        transmission: 'Automatic',
        AC: "Yes",
        Fuel: 'Electric',
    },
    {
        id: 1,
        make: 'Mercedes-Benz',
        price: 85,
        image:'../images/metallic-glacierwhite.jpg',
        model: 'A1',
        year: 2017,
        transmission: 'Automatic',
        AC: "No",
        Fuel: 'Petrol',
    },
    {
        id: 2,
        make: 'Audi',
        price: 25,
        image:'../images/audi-s3-2020-2022-1627798082.0710783.jpg',
        model: 'S3',
        year: 2020,
        transmission: 'Automatic',
        AC: "Yes",
        Fuel: 'Gas',
    },
    {
        id: 3,
        make: 'Kia',
        price: 25,
        image:'../images/kia_cerato_ii_sedan_1.jpg',
        model: 'Cerato II',
        year: 2017,
        transmission: 'Hybrid',
        AC: "Yes",
        Fuel: 'Petrol',
    },
    {
        id: 4,
        make: 'Kia',
        price: 25,
        image:'../images/bd_frontquarter_horizon-blue_bbl.jpg',
        model: 'Horizon',
        year: 2014,
        transmission: 'Manuel',
        AC: "Yes",
        Fuel: 'Petrol',
    },
    {
        id: 5,
        make: 'BMW',
        price: 25,
        image:'../images/bmw320.84ab73b0c9133418f907.jpg',
        model: '3 series',
        year: 2015,
        transmission: 'Manuel',
        AC: "Yes",
        Fuel: 'Petrol',
    },

]